
CL-USER 1 > (numProd 3)

Error: Undefined operator NUMPROD in form (NUMPROD 3).
  1 (continue) Try invoking NUMPROD again.
  2 Return some values from the form (NUMPROD 3).
  3 Try invoking something other than NUMPROD with the same arguments.
  4 Set the symbol-function of NUMPROD to another function.
  5 Set the macro-function of NUMPROD to another function.
  6 (abort) Return to top loop level 0.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

CL-USER 2 : 1 > 